AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS Serverless Spring Boot 3 API - com.sergio::java-lambda
Globals:
  Api:
    EndpointConfiguration: REGIONAL

Resources:
  JavaLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.eommt.StreamLambdaHandler::handleRequest
      Runtime: java21
      CodeUri: .
      MemorySize: 512
      Policies: AWSLambdaBasicExecutionRole
      Timeout: 30
      Environment:
        Variables:
          SPRING_PROFILES_ACTIVE: production
          DB_HOST: apieommt-test2.ckp2ww6u8gac.us-east-1.rds.amazonaws.com
          DB_PORT: 5432
          DB_NAME: test
          DB_USER: postgres
          DB_PASSWORD: 0f54rkrCo31j
      Events:
        ProxyResource:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: any

Outputs:
  JavaLambdaApi:
    Description: URL for application
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/ping'
    Export:
      Name: JavaLambdaApi
